name: CI - Microservices

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        service: [common, product-service, order-service, payment-service]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean verify
        working-directory: ./${{ matrix.service }}

  create-pr:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Create PR from develop to master
        uses: peter-evans/create-pull-request@v5
        with:
          base: master
          branch: develop
          title: 'Sync develop -> master'
          body: 'Automated PR from develop to master after successful CI build'
